### ISSUE TITLE
Review: potential issues/questions

### ISSUE THREAD

**Issue by boris-kolpackov** [EmilRosenquist/mini_chromium#1]
I've pushed my partial review to the `review-boris` branch. Additional:

1. Tests come in a separate package but they don't depend on anything extra (e.g., a testing framework) so it's unclear why this arrangement is necessary? Do upstream tests depend on something and is this future-proofing?

2. I see that the test includes the header as `<base/...>` -- that's pretty loose since `base` has nothing to do with the library name and is thus prone to clashes. I realize it's possible there is not much we can do about this but I would like to confirm. Are all users of this library include its headers like this? Ideally we would want to change this to something like `<mini_chromium/base/...>`. Maybe we should support both ways.

Even if we do continue down this route, when installed, the headers should go into the `mini_chromium` subdirectory. See for example how this is done in `fakeit`: https://github.com/build2-packaging/fakeit/blob/main/fakeit/buildfile#L27-L40

3. Please stop thoughtlessly copying compile options from upstream -- cleaning them up is wasting a lot of my time. See my numerous comments in the  `buildfile`.

**Comment by EmilRosenquist** [comment]
@boris-kolpackov 
1. This was done because the upstream tests do use `gtest`, but after then taking a closer look to the upstream tests these were not used and I did not redo it (I can do that if we feel it would benefit).

2. Yes I would rather want it to be `<mini_chromium/base/...>` but since the current consumers use `<base/...>`, If we can support both ways that would be optimal. Ill look into that.

3. ~~Not sure exactly how to go about this then. I have copied the hardcoded flags from upstream because this is specified by their build system. I can ignore these but I would suspect this would cause issues with the upstream library since it (could possibly) depends on some of these eg.  `-D_FILE_OFFSET_BITS=64` `-DUNICODE`. And not sure what the downside is to using the same flags as upstream, as I would see it beneficial to use the same as upstream to avoid any differences.~~
Already answered in https://github.com/build2/HOWTO/blob/master/entries/compile-options-in-buildfile.md

**Comment by EmilRosenquist** [comment]
And regarding a comment in the review branch
https://github.com/build2-packaging/mini_chromium/blob/b87fe813d3c066c6046f0f5b0c5a6b136b94df29/mini_chromium/mini_chromium/buildfile#L152-L159.
If I don't have this for `advapi32.lib` I get this error
```
rand_util.dll.obj : error LNK2019: unresolved external symbol SystemFunction036 referenced in function "void __cdecl base::RandBytes(void *,unsigned __int64)" (?RandBytes@base@@YAXPEAX_K@Z)
..\mini_chromium-msvc\mini_chromium\mini_chromium\mini_chromium-0.1.0-a.0.20220905121314.dll : fatal error LNK1120: 1 unresolved externals
```
So if they are suppose to be automatically linked there seems to be something wrong or something else missing.
See here https://ci.stage.build2.org/@2241ae1a-23e2-4aae-8338-485685b1769d/mini_chromium/0.1.0-a.0.20220905134926.be53e4514301/log/windows_10-msvc_16.11-O2/x86_64-microsoft-win32-msvc14.2/stage/0.16.0-a.0.20220902091207.e5444ac427dc/test

**Comment by EmilRosenquist** [comment]
After the changes in https://github.com/build2-packaging/mini_chromium/commit/b87fe813d3c066c6046f0f5b0c5a6b136b94df29#diff-997af1701903be249d2acc05dfa15054d7bf1d9542874ce84681e7888ccca50bR231. The macos build fails and doesn't find the files see here https://ci.stage.build2.org/@2241ae1a-23e2-4aae-8338-485685b1769d/mini_chromium/0.1.0-a.0.20220905134926.be53e4514301/log/macos_11-clang_13.0/x86_64-apple-darwin20.5.0/stage/0.16.0-a.0.20220902091207.e5444ac427dc/test

**Comment by boris-kolpackov** [comment]
> This was done because the upstream tests do use `gtest`, but after then taking a closer look to the upstream tests these were not used and I did not redo it (I can do that if we feel it would benefit).

Ok, let's keep it as a separate package for now, in case on another look we do need `gtest` after all.

> If I don't have this for `advapi32.lib` I get this error [...]

Ok, I stand corrected, I guess MSVC doesn't link this one by default (but MinGW does).

> After the changes in [...] the macos build fails and doesn't find the files

Hm, I don't think it's because of the `-I` change. Looks like these files are not distributed for some reason. I will look into it.

**Comment by boris-kolpackov** [comment]
Ok, I believe all of these are resolved.
